[variables]
NPM_CONFIG_PRODUCTION = 'false'

[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'cd client',
  'npm install', 
  'npm run build',
  'cd ..'
]

[start]
cmd = 'npm start'